config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'about_us' => 'home#about_us', as: 'about_us'
  get 'consumers' => 'home#consumers', as: 'consumers'
  get 'enterprises' => 'home#enterprises', as: 'enterprises'
  get 'beta_invite' => 'home#beta_invite', as: 'beta_invite'
  get 'privacy_policy' => 'home#privacy_policy', as: 'privacy_policy'
  get 'terms_of_service' => 'home#terms_of_service', as: 'terms_of_service'
  resources :contacts, only: %i[new create update]
  get 'contacts/thank_you' => 'contacts#thank_you', as: :thank_you

  devise_for :users,
             :controllers => {
                  registrations: 'users/registrations',
                  sessions:      'users/sessions',
                  invitations:   'users/invitations'
             }
  get '/openid_auth', to: 'openid#openid_auth', as: 'openid_auth'
  get '/openid_auth_callback', to: 'openid#openid_auth_callback', as: 'openid_auth_callback'
  post '/openid_register', to: 'openid#openid_register', as: 'openid_register'


  get '/welcome', to: 'welcome#index', as: 'welcome'
  get '/mobile-apps', to: 'setup#mobile_apps', as: 'mobile-apps'
  get '/sample-apps', to: 'setup#sample_apps', as: 'sample-apps'
  get '/get-started', to: 'setup#get_started', as: 'get-started'
  get '/pricing', to: 'setup#pricing', as: 'pricing'
  get '/analytics', to: 'analytics#index', as: 'analytics'
  get '/user_growth_json_data', to: 'analytics#user_growth_json_data'
  get '/logs', to: 'analytics#logs', as: 'logs'
  get '/manage', to: 'manage#index', as: 'manage'

  resources :accounts
  # resources :users
  resources :apps
  resources :subscriptions


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'application'

  def index
    # code
  end

  def about_us
    # code
  end

  def contact
    # code
  end

  def consumers
    
  end

  def enterprises
    
  end

  def pricing
    # code
  end

  def privacy_policy
    # code
  end

  def terms_of_service
    # code
  end
end

app/views/home/_features.html.erb
<!-- ========== FEATURES ========== -->
<section class="se-section features-section parallax-bg" data-parallax="scroll" data-image-src="images/bg-img-3.jpg" data-speed="0.4">
  <div class="black-gradient">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-6 se-feature-style-2 mb60">
          <div class="left">
            <i class="icon ion-arrow-expand"></i>
          </div>
          <div class="right">
            <h5>Fully Responsive</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
          </div>
        </div>
        <!-- end se-feature -->

        <div class="col-md-6 col-sm-6 se-feature-style-2 mb60">
          <div class="left">
            <i class="icon ion-android-search"></i>
          </div>
          <div class="right">
            <h5>Retina Ready</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
          </div>
        </div>
        <!-- end se-feature -->

        <div class="col-md-6 col-sm-6 se-feature-style-2 mb60">
          <div class="left">
            <i class="icon ion-ios-bolt"></i>
          </div>
          <div class="right">
            <h5>Lightning Fast</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
          </div>
        </div>
        <!-- end se-feature -->

        <div class="col-md-6 col-sm-6 se-feature-style-2 mb60">
          <div class="left">
            <i class="icon ion-information"></i>
          </div>
          <div class="right">
            <h5>Google Fonts</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
          </div>
        </div>
        <!-- end se-feature -->

        <div class="col-md-6 col-sm-6 se-feature-style-2">
          <div class="left">
            <i class="icon ion-checkmark"></i>
          </div>
          <div class="right">
            <h5>Light Weight</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
          </div>
        </div>
        <!-- end se-feature -->

        <div class="col-md-6 col-sm-6 se-feature-style-2">
          <div class="left">
            <i class="icon ion-settings"></i>
          </div>
          <div class="right">
            <h5>Easy To Edit</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
          </div>
        </div>
        <!-- end se-feature -->

      </div>
      <!-- end row -->
    </div>
    <!-- end container -->
  </div>
  <!-- end black-gradient -->
</section>
<!-- end features-section -->

app/views/home/beta_invite.html.erb
<header class="header main-header header-style-2" id="circular-particles">
  <div class="primary-trans-bg">
    <div class="container">
      <div class="outer">
        <div class="inner text-center">
          <br>
          <br>
          <h1 class="white-color">
            Deauthorized is in a private beta.
            <br/>Sign up here to get an invite.
          </h1>
          <!-- <h5 class="">Deauthorized is a FIDO Approved U2F and UAF product that helps businesses prevent account takeover with decentralized, secure, biometric authentication. </h5> -->
          <div class="col-md-6 col-md-offset-3">
            <br>
            <br>
            <br>
            <script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
            <script>
              hbspt.forms.create({
                portalId: '3970341',
                formId: '70172187-f095-451f-a781-0cd4a2c6fc0f'
              });
            </script>
          </div>

        </div>
      </div>
    </div>
  </div>
</header>

app/views/home/consumers.html.erb
<!-- ========== HEADER ========== -->
<header class="header main-header header-style-2" id="circular-particles">
  <div class="primary-trans-bg">
    <div class="container">
      <div class="outer">
        <div class="inner text-center">
          <h1 class="white-color">Keep All Your Online Accounts Safe.
            <br/>
            No Matter What.</h1>
          <h5 class="">Our system empowers you to keep control of your accounts even if they are hacked.</h5>
        </div>
      </div>
    </div>
  </div>
</header>
<section class="se-section features-section">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-12 se-feature">
        <i class="icon ion-radio-waves"></i>
        <h5>Keep Control</h5>
        <p> Our system uses biometric info so only you can authorize the shutdowns </p>
      </div>
      <div class="col-md-4 col-sm-12 se-feature">
        <i class="icon ion-ios-paper-outline"></i>
        <h5>Protect Everything
        </h5>
        <p>Notify your banks, mobile wallet provider, and social media provider to suspend all user activity.</p>
      </div>
      <div class="col-md-4 col-sm-12 se-feature">
        <i class="icon ion-ios-lightbulb-outline"></i>
        <h5>Secure Accounts</h5>
        <p>Get your accounts back with a direct line of communication to every provider.</p>
      </div>
    </div>
  </div>
</section>


        <section class="se-section single-feature">

  <div class="col-md-6 zero-padding col-md-push-6 side-img">
    <img src="https://placehold.it/1600x1000?text=Mobile%20App" alt="" class="img-responsive">
  </div>
  <!-- end side-img -->

  <div class="container feature-desc">
    <div class="row">
      <div class="col-md-5 feature-info">
        <h2>Protect your digital life with a single app
        </h2>
        <p>When hackers obtain peices of your personal identifiable information, they use that info to infiltrate your financial accounts, email, and social media. Once they have taken over some of your personal information, the attacks can quickly escalate
          to many other accounts.
        </p>
        <p>Deauthorized is an kill switch that suspends your user activity on an app, prevents escalation of attacks to other services, and helps you regain control of compromised accounts.</p>
        <%= link_to "Learn More", pricing_path, class: "btn se-btn btn-rounded" %>

      </div>

    </div>
    <!-- end row -->
  </div>
  <!-- end container -->

</section>

<!-- ========== STEPS ========== -->
<section class="se-section se-steps">
  <div class="container">
    <div class="row text-center">
      <h3 class="underline mtn">It's as ease as 1 - 2 - 3!</h3>
    </div>
    <!-- end row -->

    <div class="row">
      <div class="col-md-4 col-sm-4 one-step">
        <h4>Download Our Mobile App</h4>
        <p>Use our mobile application to create your secure identity on the blockchain.
        </p>
      </div>

      <div class="col-md-4 col-sm-4 one-step">
        <h4>Sign Up for an Account
        </h4>
        <p>Use the mobile app to authenticate via a single sign-on, biometric authenticator.
        </p>
      </div>

      <div class="col-md-4 col-sm-4 one-step">
        <h4>Connect with Your Services</h4>
        <p>Integrate your online financial accounts, email accounts, mobile providers, and more.</p>
      </div>
    </div>
    <!-- end row -->
  </div>
  <!-- end container -->
</section>

<!-- ========== CTA SECTION ========== -->
<section class="se-section primary-bg">
  <div class="container">
    <div class="row text-center">
      <h3>Create Your Account Now!</h3>
      <p>Sign Up for Free. No credit card required.</p>
      <%= link_to "SIGN UP", new_user_registration_path, class: "btn se-btn-black btn-rounded" %>
    </div>
    <!-- end row -->
  </div>
  <!-- end container -->
</section>

app/views/home/enterprises.html.erb
<!-- ========== HEADER ========== -->
<header class="header main-header header-style-2" id="circular-particles">
  <div class="primary-trans-bg">
    <div class="container">
      <div class="outer">
        <div class="inner text-center">
          <h1 class="white-color">Equip Customers and Employees
            <br/> to Prevent Account Takeover</h1>
          <h5 class="">Deauthorized's SaaS application is a fast, flexible, and secure way for businesses to scale up strong authentication, eliminate fraud, save millions on password resets, and simplify the user authentication experience.</h5>
        </div>
      </div>
    </div>
  </div>
</header>

<section class="se-section">
  <div class="container">
    <div class="row">

      <div class="col-md-4 col-sm-6 se-feature-style-3">
        <div class="feature-wrap">
          <i class="icon ion-ios-analytics-outline"></i>
          <h5>Risk Mitigation</h5>
          <p>Reduce the risk of data breaches and liability from account takeover fraud.</p>
        </div>
      </div>

      <div class="col-md-4 col-sm-6 se-feature-style-3">
        <div class="feature-wrap">
          <i class="icon ion-ios-paper-outline"></i>
          <h5>Protect Customers</h5>
          <p>Provide your customers and employees with the gold standard in secure authenication.</p>
        </div>
      </div>

      <div class="col-md-4 col-sm-6 se-feature-style-3">
        <div class="feature-wrap">
          <i class="icon ion-ios-lightbulb-outline"></i>
          <h5>Secure Communication</h5>
          <p>Keep all your online accounts safe. No matter what.</p>
        </div>
      </div>
      <!-- <div class="col-md-6 col-sm-6 se-feature-style-3"> <div class="feature-wrap"> <i class="icon ion-outlet"></i> <h5>Font Icons</h5> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
      magna aliqua.</p> </div> </div> <div class="col-md-6 col-sm-6 se-feature-style-3"> <div class="feature-wrap"> <i class="icon ion-ios-bolt-outline"></i> <h5>Lightning Fast</h5> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod tempor incididunt ut labore et dolore magna aliqua.</p> </div> </div> -->
    </div>
    <!-- end row -->
  </div>
  <!-- end container -->
</section>

<!-- ========== SINGLE FEATURE SECTION ========== -->
<section class="se-section single-feature">

  <div class="col-md-6 zero-padding side-img">
    <%= image_tag('dash.png', class: 'img-responsive') %>
  </div>
  <!-- end side-img -->

  <div class="container feature-desc">
    <div class="row">
      <div class="col-md-5 col-md-push-7 feature-info">
        <h2>Preserve reputation with customers</h2>
        <p>As security breaches become more prevelant and hackers become more sophisticated, businesses need proven security standards such as FIDO to prevent fraud and stop bad actors online.
        </p>
        <p>Deauthorized is here to help your business secure your enteprise from risk of data breaches and prevent account takeover fraud altogether. We provide mobile apps for biometric authentication, a FIDO U2F and UAF server, and secure dashboard that
          manages trusted ID's from millions of consumers to your applications, logins, and infrastructure.
        </p>
        <%= link_to "Get in the Beta", beta_invite_path, class: "btn se-btn btn-rounded" %>
      </div>
    </div>

    <!-- end row -->
  </div>
  <!-- end container -->
</section>

<section class="se-section single-feature">

  <div class="col-md-6 zero-padding col-md-push-6 side-img">
    <div class="row">
      <div class="col-md-6 text-center">
        <%= image_tag('da-mobile-app.png', size: '275x550') %>
      </div>
      <div class="col-md-6 text-center">

        <div class="">
          <div class="row">
            <div class="">
              <div class="da-box">
                <div class="branding-box text-center">
                  <div class="branding"></div>
                </div>
                <div class="smooth-box text-center">
                  <div class="qr-code"></div>
                  <a class="btn btn-lg btn-brand">Enter</a>

                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
  <!-- end side-img -->

  <div class="container feature-desc">
    <div class="row">
      <div class="col-md-5 feature-info">
        <h2>Secure your online identity with a single mobile app
        </h2>
        <p>When cyber criminals steal data from businesses online, they use that info to infiltrate your work, financial accounts, email, and social media. Once they have your email and password, its game over.
        </p>
        <p>Deauthorized is a passwordless authentication mobile app that uses TouchID and FaceID on your mobile device to authenicate you into an app, website, your car, or a door to a building. With Deauthorized, you will never have to remember another
          password ever again.</p>
        <%= link_to "Get in the Beta", beta_invite_path, class: "btn se-btn btn-rounded" %>

      </div>

    </div>
    <!-- end row -->
  </div>
  <!-- end container -->

</section>

app/views/home/index.html.erb
<!-- ========== HEADER ========== -->
<header class="header main-header header-style-2" id="circular-particles">
  <div class="primary-trans-bg">
    <div class="container">
      <div class="outer">
        <div class="inner text-center">
          <h1 class="white-color">
            Protecting Everyone from
            <br/>Account Takeover
          </h1>
          <h5 class="">Deauthorized is a FIDO Approved U2F and UAF product that helps businesses prevent account takeover with decentralized, secure, biometric authentication.
          </h5>
        </div>
      </div>
    </div>
  </div>
</header>
<section class="se-section features-section">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-12 se-feature">
        <i class="icon ion-radio-waves"></i>
        <h5>Eliminate Fraud</h5>
        <p>
          Our system uses biometric authenitcation so only verified customers can login or authorize transactions.
        </p>
      </div>
      <div class="col-md-4 col-sm-12 se-feature">
        <i class="icon ion-ios-paper-outline"></i>
        <h5>Reduce Data Breaches
        </h5>
        <p>Removing user credentials from your application database leaves nothing for hackers to steal.</p>
      </div>
      <div class="col-md-4 col-sm-12 se-feature">
        <i class="icon ion-ios-lightbulb-outline"></i>
        <h5>Enhance User Experience</h5>
        <p>Login or register with passwordless authentication using TouchId or FaceId.</p>
      </div>
    </div>
  </div>
</section>

<!-- ========== STEPS ========== -->
<section class="se-section se-steps">
  <div class="container">
    <div class="row text-center">
      <h3 class="underline mtn">It's as easy as 1 - 2 - 3!</h3>
      <div class="row">
        <div class="col-md-6 text-center">
          <%= image_tag('da-mobile-app.png', size: '275x550') %>
        </div>
        <div class="col-md-6 text-center">

          <div class="">
            <div class="row">
              <div class="">
                <div class="da-box">
                  <div class="branding-box text-center">
                    <div class="branding"></div>
                  </div>
                  <div class="smooth-box text-center">
                    <div class="qr-code"></div>
                    <a class="btn btn-lg btn-brand">Enter</a>

                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-md-4 col-sm-4 one-step">
        <h4>Download Our Mobile App</h4>
        <p>Download our mobile application to create your account.
        </p>
      </div>

      <div class="col-md-4 col-sm-4 one-step">
        <h4>Sign Up for an Account
        </h4>
        <p>Use the mobile app to authenticate via a single sign-on, biometric authenticator.
        </p>
      </div>

      <div class="col-md-4 col-sm-4 one-step">
        <h4>Connect with Your Services</h4>
        <p>Integrate your online financial accounts, email accounts, mobile providers, and more.</p>
      </div>
    </div>
  </div>
</section>

<!-- ========== CTA SECTION ========== -->
<section class="se-section primary-bg">
  <div class="container">
    <div class="row text-center">
      <h3>Sign up for a limited beta!</h3>
      <p>The first 10 users in the beta will receive our service free forever.</p>
      <%= link_to "SIGN UP", beta_invite_path, class: "btn se-btn-black btn-rounded" %>
    </div>
    <!-- end row -->
  </div>
  <!-- end container -->
</section>

app/views/home/privacy_policy.html.erb
<!-- ========== PAGE TITLE ========== -->
<header class="header page-title">
  <div class="container">
    <!-- For centering the content vertically -->
    <div class="outer">
      <div class="inner text-center">
        <div class="breadcrumb">
          <%= link_to "Home", root_path  %>
          <i class="icon ion-chevron-right"></i>
          <%= link_to "Privacy Policy", privacy_policy_path  %>
        </div>
        <!-- end breadcrumb -->

        <h1 class="">Privacy Policy
        </h1>
        <h5 class="">Last updated: September 12, 2017</h5>

      </div>
      <!-- end inner -->
    </div>
    <!-- end outer -->
  </div>
  <!-- end container -->
</header>

<!-- ========== PRIVACY POLICY SECTION ========== -->
<section class="se-section pp-section">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">

        <h1>Privacy Policy</h1>

        <p>Deauthorized Corporation ("us", "we", or "our") operates the https://deauthorized.com website (the "Service").</p>

        <p>This page informs you of our policies regarding the collection, use and disclosure of Personal Information when you use our Service.</p>

        <p>We will not use or share your information with anyone except as described in this Privacy Policy.</p>

        <p>We use your Personal Information for providing and improving the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this
          Privacy Policy have the same meanings as in our Terms and Conditions, accessible at https://deauthorized.com</p>

        <h5 class="underline">Information Collection And Use</h5>

        <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to, your email address, name,
          phone number ("Personal Information").</p>

        <p>We collect this information for the purpose of providing the Service, identifying and communicating with you, responding to your requests/inquiries, servicing your purchase orders, and improving our services.</p>

        <h5 class="underline">Log Data</h5>

        <p>We may also collect information that your browser sends whenever you visit our Service ("Log Data"). This Log Data may include information such as your computer's Internet Protocol ("IP") address, browser type, browser version, the pages of our
          Service that you visit, the time and date of your visit, the time spent on those pages and other statistics.</p>

        <p>In addition, we may use third party services such as Google Analytics that collect, monitor and analyze this type of information in order to increase our Service's functionality. These third party service providers have their own privacy policies
          addressing how they use such information.</p>

        <h5 class="underline">Cookies</h5>

        <p>Cookies are files with a small amount of data, which may include an anonymous unique identifier. Cookies are sent to your browser from a web site and transferred to your device. We use cookies to collect information in order to improve our
          services for you.</p>

        <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. The Help feature on most browsers provide information on how to accept cookies, disable cookies or to notify you when receiving a new cookie.</p>

        <p>If you do not accept cookies, you may not be able to use some features of our Service and we recommend that you leave them turned on.</p>

        <h5 class="underline">Do Not Track Disclosure</h5>

        <p>We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p>

        <p>You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>

        <h5 class="underline">Service Providers</h5>

        <p>We may employ third party companies and individuals to facilitate our Service, to provide the Service on our behalf, to perform Service-related services and/or to assist us in analyzing how our Service is used.</p>

        <p>These third parties have access to your Personal Information only to perform specific tasks on our behalf and are obligated not to disclose or use your information for any other purpose.</p>

        <h5 class="underline">Communications</h5>

        <p>We may use your Personal Information to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following
          the unsubscribe link or instructions provided in any email we send or by contacting us.</p>

        <h5 class="underline">Compliance With Laws</h5>

        <p>We will disclose your Personal Information where required to do so by law or subpoena or if we believe that such action is necessary to comply with the law and the reasonable requests of law enforcement or to protect the security or integrity of
          our Service.</p>

        <h5 class="underline">Business Transaction</h5>

        <p>If Deauthorized Corporation is involved in a merger, acquisition or asset sale, your Personal Information may be transferred as a business asset. In such cases, we will provide notice before your Personal Information is transferred and/or becomes
          subject to a different Privacy Policy.</p>

        <h5 class="underline">Security</h5>

        <p>The security of your Personal Information is important to us, and we strive to implement and maintain reasonable, commercially acceptable security procedures and practices appropriate to the nature of the information we store, in order to protect
          it from unauthorized access, destruction, use, modification, or disclosure.</p>

        <p>However, please be aware that no method of transmission over the internet, or method of electronic storage is 100% secure and we are unable to guarantee the absolute security of the Personal Information we have collected from you.</p>

        <h5 class="underline">International Transfer</h5>

        <p>Your information, including Personal Information, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from
          your jurisdiction.</p>

        <p>If you are located outside United States and choose to provide information to us, please note that we transfer the information, including Personal Information, to United States and process it there.</p>

        <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>

        <h5 class="underline">Links To Other Sites</h5>

        <p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>

        <p>We have no control over, and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

        <h5 class="underline">Children's Privacy</h5>

        <p>Only persons age 18 or older have permission to access our Service. Our Service does not address anyone under the age of 13 ("Children").</p>

        <p>We do not knowingly collect personally identifiable information from children under 13. If you are a parent or guardian and you learn that your Children have provided us with Personal Information, please contact us. If we become aware that we have
          collected Personal Information from a children under age 13 without verification of parental consent, we take steps to remove that information from our servers.</p>

        <h5 class="underline">Changes To This Privacy Policy</h5>

        <p>This Privacy Policy is effective as of September 12, 2017 and will remain in effect except with respect to any changes in its provisions in the future, which will be in effect immediately after being posted on this page.</p>

        <p>We reserve the right to update or change our Privacy Policy at any time and you should check this Privacy Policy periodically. Your continued use of the Service after we post any modifications to the Privacy Policy on this page will constitute
          your acknowledgment of the modifications and your consent to abide and be bound by the modified Privacy Policy.</p>

        <p>If we make any material changes to this Privacy Policy, we will notify you either through the email address you have provided us, or by placing a prominent notice on our website.</p>

        <h5 class="underline">Contact Us</h5>

        <p>If you have any questions about this Privacy Policy, please contact us.</p>

      </div>
    </div>
    <!-- end row -->
  </div>
  <!-- end container -->
</section>

<!-- ========== CTA SECTION ========== -->
<section class="se-section primary-bg">
  <div class="container">
    <div class="row text-center">
      <h3>Create Your Account Now!</h3>
      <p>Get 30 days trial. No credit card required.</p>
      <%= link_to "SIGN UP", new_user_registration_path, class: "btn se-btn-black btn-rounded" %>
    </div>
    <!-- end row -->
  </div>
  <!-- end container -->
</section>