config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'about_us' => 'home#about_us', as: 'about_us'
  get 'consumers' => 'home#consumers', as: 'consumers'
  get 'enterprises' => 'home#enterprises', as: 'enterprises'
  get 'beta_invite' => 'home#beta_invite', as: 'beta_invite'
  get 'privacy_policy' => 'home#privacy_policy', as: 'privacy_policy'
  get 'terms_of_service' => 'home#terms_of_service', as: 'terms_of_service'
  resources :contacts, only: %i[new create update]
  get 'contacts/thank_you' => 'contacts#thank_you', as: :thank_you

  devise_for :users,
             :controllers => {
                  registrations: 'users/registrations',
                  sessions:      'users/sessions',
                  invitations:   'users/invitations'
             }
  get '/openid_auth', to: 'openid#openid_auth', as: 'openid_auth'
  get '/openid_auth_callback', to: 'openid#openid_auth_callback', as: 'openid_auth_callback'
  post '/openid_register', to: 'openid#openid_register', as: 'openid_register'


  get '/welcome', to: 'welcome#index', as: 'welcome'
  get '/mobile-apps', to: 'setup#mobile_apps', as: 'mobile-apps'
  get '/sample-apps', to: 'setup#sample_apps', as: 'sample-apps'
  get '/get-started', to: 'setup#get_started', as: 'get-started'
  get '/pricing', to: 'setup#pricing', as: 'pricing'
  get '/analytics', to: 'analytics#index', as: 'analytics'
  get '/user_growth_json_data', to: 'analytics#user_growth_json_data'
  get '/logs', to: 'analytics#logs', as: 'logs'
  get '/manage', to: 'manage#index', as: 'manage'

  resources :accounts
  # resources :users
  resources :apps
  resources :subscriptions


end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :user

	validates :user_id, uniqueness: true
	validates :plan_id, presence: true
	validates :customer_id, presence: true
	validates :subscription_id, presence: true
end

app/views/subscriptions/index.html.erb
<section>
  <h2 class="text-center">Select your plan</h2>

  <div class="row">
    <div class="col-md-4">
      <ul class="price">
        <li class="header">Basic</li>
        <li class="grey">$10.0 / Month</li>
        <li>10GB Storage</li>
        <li>10 Emails</li>
        <li>10 Domains</li>
        <li>1GB Bandwidth</li>
        <li class="grey">
          <%= link_to "Sign Up", new_users_subscription_path(plan_id: "basic"), class: "btn btn-primary" %>
        </li>
      </ul>
    </div>

    <div class="col-md-4">
      <ul class="price">
        <li class="header">Premium</li>
        <li class="grey">$20.0 / Month</li>
        <li>25GB Storage</li>
        <li>25 Emails</li>
        <li>25 Domains</li>
        <li>2GB Bandwidth</li>
        <li class="grey">
          <%= link_to 'Sign Up', new_users_subscription_path(plan_id: "premium"), class: "btn btn-primary" %>
        </li>
      </ul>
    </div>

    <div class="col-md-4">
      <ul class="price">
        <li class="header">Enterprize</li>
        <li class="grey">$100.0 / 3 Months</li>
        <li>50GB Storage</li>
        <li>50 Emails</li>
        <li>50 Domains</li>
        <li>5GB Bandwidth</li>
        <li class="grey">
          <%= link_to 'Sign Up', new_users_subscription_path(plan_id: "enterpize"), class: "btn btn-primary" %>
        </li>
      </ul>
    </div>
  </div>
</section>

app/views/subscriptions/new.html.erb
<div class="wrapper">
  <div class="checkout">
    <div class="content">

      <header>
        <h2>Select your paymen method.</h2>
      </header>

      <%= form_for @subscription, url: users_subscriptions_path, method: :post, html: { id: "payment-form" } do |f| %>
        <%= f.hidden_field :plan_id, value: @subscription.plan_id %>
        <div class="bt-drop-in-wrapper">
          <div id="bt-dropin"></div>
        </div>

        <input type="hidden" id="nonce" name="payment_method_nonce" />
        <button class="btn btn-primary" type="submit"><span>Apply</span></button>
      <% end %>
    </div>
  </div>
</div>

<script src="https://js.braintreegateway.com/web/dropin/1.9.4/js/dropin.min.js"></script>
<script>
  var form = document.querySelector('#payment-form');
  var client_token = "<%= @client_token %>";

  braintree.dropin.create({
    authorization: client_token,
    container: '#bt-dropin',
    paypal: {
      flow: 'vault'
    }
  }, function (createErr, instance) {
    form.addEventListener('submit', function (event) {
      event.preventDefault();

      instance.requestPaymentMethod(function (err, payload) {
        if (err) {
          console.log('Error', err);
          return;
        }

        // Add the nonce to the form and submit
        document.querySelector('#nonce').value = payload.nonce;
        form.submit();
      });
    });
  });
</script>