config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'about_us' => 'home#about_us', as: 'about_us'
  get 'consumers' => 'home#consumers', as: 'consumers'
  get 'enterprises' => 'home#enterprises', as: 'enterprises'
  get 'beta_invite' => 'home#beta_invite', as: 'beta_invite'
  get 'privacy_policy' => 'home#privacy_policy', as: 'privacy_policy'
  get 'terms_of_service' => 'home#terms_of_service', as: 'terms_of_service'
  resources :contacts, only: %i[new create update]
  get 'contacts/thank_you' => 'contacts#thank_you', as: :thank_you

  devise_for :users,
             :controllers => {
                  registrations: 'users/registrations',
                  sessions:      'users/sessions',
                  invitations:   'users/invitations'
             }
  get '/openid_auth', to: 'openid#openid_auth', as: 'openid_auth'
  get '/openid_auth_callback', to: 'openid#openid_auth_callback', as: 'openid_auth_callback'
  post '/openid_register', to: 'openid#openid_register', as: 'openid_register'


  get '/welcome', to: 'welcome#index', as: 'welcome'
  get '/mobile-apps', to: 'setup#mobile_apps', as: 'mobile-apps'
  get '/sample-apps', to: 'setup#sample_apps', as: 'sample-apps'
  get '/get-started', to: 'setup#get_started', as: 'get-started'
  get '/pricing', to: 'setup#pricing', as: 'pricing'
  get '/analytics', to: 'analytics#index', as: 'analytics'
  get '/user_growth_json_data', to: 'analytics#user_growth_json_data'
  get '/logs', to: 'analytics#logs', as: 'logs'
  get '/manage', to: 'manage#index', as: 'manage'

  resources :accounts
  # resources :users
  resources :apps
  resources :subscriptions


end

app/views/apps/_app.html.erb
<tr>
  <td>
    <%= link_to app_path(app) do  %>
      <%= app.name %>
        <% end %>
  </td>
  <td>
    <%= app.openid_redirect_urls %>
  </td>
  <td>
    <%= app.platform %>
  </td>
  <td>
    <%= link_to 'Edit App', edit_app_path(app) %>
  </td>
  <td>
    <%= link_to 'Delete App', app_path(app), method: :delete, data: { confirm: 'Are you sure? This will remove the client id from the server and you will no longer be able to authenticate.' } %>
  </td>

</tr>

app/views/apps/_form.html.erb
<%= form_for(@app, local: true) do |form| %>

  <% if app.errors.any? %>
    <div class="error_explanation">
      <ul>
        <% app.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= form.label :name, "Client Name (client_name)" %> <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="The name of your application."></i>

              <%= form.text_field :name, class: "form-control", placeholder: "Acme Node Application" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= form.label :client_uri, "Website / Domain URL (client_uri)" %> <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="The website URL that is using us for identity management. "></i>
              <%= form.text_field :client_uri, class: "form-control", placeholder: "https://acme.com" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= form.label :logo_uri, "App Logo (logo_uri)" %> <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="A URL / link to your logo or brand for your application or service. Please use a 100px X 100px square or circular image."></i>
              <%= form.text_field :logo_uri, class: "form-control", placeholder: "https://acme.com/logo.png" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= form.label :contacts, "Contact Email (contacts)" %> <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="The contact information for the person or organization who is supporting this application - support@acme.com "></i>

              <%= form.text_field :contacts, class: "form-control", placeholder: "support@acme.com" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= form.label :policy_uri, "Policy Webpage (policy_uri)" %> <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="The website URL that hosts your privacy policy for user data privacy or GDPR compliance. "></i>
              <%= form.text_field :policy_uri, class: "form-control", placeholder: "https://acme.com/policy" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= form.label :tos_uri, "Terms of Service Webpage (tos_uri) " %> <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="The website URL that hosts your terms of service for users. "></i>
              <%= form.text_field :tos_uri, class: "form-control", placeholder: "https://acme.com/tos" %>

          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= form.label :platform, "Application Type (application_type)" %> <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="Web or mobile strategy. "></i>
              <%= form.select :platform, [['Web', 'web']], {}, { class: "form-control", disabled: !app.new_record? } %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= form.label :token_endpoint_auth_method, "Token Endpoint (token_endpoint_auth_method)" %> <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="The token endpoint auth method determines how you connect with our identity provider. Our OP supports all 5 methods. If you are rolling your own OIDC Client and you can't connect, try changing this method."></i>
              <a href="http://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata" target="_blank"> Specs</a>
              <%= form.select :token_endpoint_auth_method, App::AUTH_METHODS, {}, {class: "form-control"}  %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <%= form.label :openid_redirect_urls, "Callback URI (redirect_uri)" %> <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="You need to provide a callback URL for your client application so that our identity provider knows where to redirect the user once they are authenticated. If you are usig a pre-rolled sample app it is usually /openid_auth_callback "></i>              <i class="far fa-gem" data-toggle="tooltip" data-placement="top" title="Rails callback URL: https:/#{myappname}.herokuapp.com/openid_auth_callback"></i>
              <i class="fab fa-python" data-toggle="tooltip" data-placement="top" title="Django callaback URL: https:/#{myappname}.herokuapp.com/openid_auth_callback "></i>
              <i class="fab fa-node" data-toggle="tooltip" data-placement="top" title="Express callback URL: https:/#{myappname}.herokuapp.com/openid_auth_callback "></i>

              <%= form.text_area :openid_redirect_urls, rows: "5", class: "form-control", placeholder: "https:/acme.com/callback" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <%= form.submit class: "btn btn-lg btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>

app/views/apps/edit.html.erb
<div>
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h3>Update configuration for
        <%= @app.name %>
      </h3>
      <br>
      <%= render 'form', app: @app %>
    </div>
  </div>
</div>

app/views/apps/index.html.erb
<h4>OpenID Client Applications</h4>
<div class="row">
  <div class="col-md-9">
    <h6>List of apps:</h6>
  </div>
  <div class="col-md-3">
    <%= link_to 'Add a New Application', new_app_path, class: "btn btn-lg btn-primary float-right" %>
  </div>
</div>
<br>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>App Name </th>
      <th>Callback URL</th>
      <th>Platform</th>
      <th colspan="2">Actions</th>
      <!-- <th colspan="3">Deploy Samples</th> -->
    </tr>
  </thead>
  <tbody>
    <%= render partial: "app", collection: @apps %>
  </tbody>
</table>

app/views/apps/new.html.erb
<div>
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h4>Create an App <br> <small>Provision an OpenID Connect Client</small> </h4>
      <p><b>Fill out the form and you'll be redirected to a configuration with all the deployment options available to you.</b></p>
      <p><b>You need to provide a Callback URL, but if you don't have a URL yet, you can go back and change it later. </b></p>

      <p>OpenID Connect allows you to register client application data with our provider. Please set your meta data according to this spec:
        <a href="http://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata" target="_blank">Open ID Connect Client
                Meta Data Specs</a>. To see what our provider supports, see the well-known configuration for our
        <a href="https://srv.qryp.to/op/.well-known/openid-configuration" target="_blank">provider.</a>
      </p>
      <p><b>All fields on this form are required</b>, but if you do not have a terms of service, policy, or logo - you can add any valid URL in the form to complete this process. If you move into production mode for real users, this information can be useful
        for them so you probably want to update it before you go live. Once we go live out of private beta, logos will be used for branded login screens. </p>
      <p>To deploy, you have several options:</p>
      <ul>
        <li>Deploy a sample to heroku </li>
        <li>Clone the sample and then deploy to heroku</li>
        <li>Roll your own OpenID Connect Client</li>
      </ul>

      <p>Heroku App Callback URL Configurations: <b>https:/#{myappname}.herokuapp.com/openid_auth_callback </b>
      </p>
      <br>
      <%= render 'form', app: @app %>
    </div>
  </div>
</div>

app/views/apps/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h2> App Configuration
        <%= link_to 'Edit App Configuration', edit_app_path, class: 'btn btn-primary float-right' %>
      </h2>
      <%= render "app_config" %>
    </div>
  </div>
  <div class="row t-60">
    <div class="col-md-10 offset-md-1">
      <h2>Deployment Options</h2>
      <hr>
    </div>
  </div>
  <div class="row t-60">
    <div class="col-md-10 offset-md-1">
      <%= render "deploy_now" %>
    </div>
  </div>
  <div class="row t-60">
    <div class="col-md-10 offset-md-1">
      <h4>2. Build it locally and deploy
      </h4>
      <p>Optionally you can build the one of the sample apps locally and the deploy to heroku with the following commands.
      </p>
      <p>Please set <b>https:/#{myappname}.herokuapp.com/openid_auth_callback</b> as the route for the callback -
        <%= link_to 'edit the Callback URL', edit_app_path %>
          <p>
            <a href="https://github.com/deauthorized" target="_blank">Sample apps on Github</a>
          </p>
          <ul class="nav nav-tabs" id="code" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="rails-tab" data-toggle="tab" href="#rails" role="tab" aria-controls="rails" aria-selected="true">Rails</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="django-tab" data-toggle="tab" href="#django" role="tab" aria-controls="django" aria-selected="false">Django</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="express-tab" data-toggle="tab" href="#express" role="tab" aria-controls="express" aria-selected="false">Express</a>
            </li>
          </ul>
          <div class="tab-content" id="codeContent">
            <div class="tab-pane fade show active" id="rails" role="tabpanel" aria-labelledby="rails-tab">
              <br>
              <%= render "rails_heroku_config" %>
            </div>
            <div class="tab-pane fade" id="django" role="tabpanel" aria-labelledby="django-tab">
              <br>
              <%= render "django_heroku_config" %>
            </div>
            <div class="tab-pane fade" id="express" role="tabpanel" aria-labelledby="express-tab">
              <br>
              <%= render "express_heroku_config" %>
            </div>
          </div>
    </div>
  </div>
  <div class="row t-60">
    <div class="col-md-10 offset-md-1">
      <h4>3. Roll an OpenID Connect Client</h4>
      <p>The OpenID spec is available online and you can roll your own authentication to connect your app to our server. </p>
      <p>
        Please read how to integrate an OpenID Connect Client in our
        <a href="https://deauthorized.github.io/documentation-0.1/#introduction" target="_blank">docs.</a>
      </p>
      <p>
        <a href="http://openid.net/developers/certified/" target="_blank">Certified OpenID Connect Implementations and Libraries</a>
      </p>
    </div>
  </div>
</div>