config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'about_us' => 'home#about_us', as: 'about_us'
  get 'consumers' => 'home#consumers', as: 'consumers'
  get 'enterprises' => 'home#enterprises', as: 'enterprises'
  get 'beta_invite' => 'home#beta_invite', as: 'beta_invite'
  get 'privacy_policy' => 'home#privacy_policy', as: 'privacy_policy'
  get 'terms_of_service' => 'home#terms_of_service', as: 'terms_of_service'
  resources :contacts, only: %i[new create update]
  get 'contacts/thank_you' => 'contacts#thank_you', as: :thank_you

  devise_for :users,
             :controllers => {
                  registrations: 'users/registrations',
                  sessions:      'users/sessions',
                  invitations:   'users/invitations'
             }
  get '/openid_auth', to: 'openid#openid_auth', as: 'openid_auth'
  get '/openid_auth_callback', to: 'openid#openid_auth_callback', as: 'openid_auth_callback'
  post '/openid_register', to: 'openid#openid_register', as: 'openid_register'


  get '/welcome', to: 'welcome#index', as: 'welcome'
  get '/mobile-apps', to: 'setup#mobile_apps', as: 'mobile-apps'
  get '/sample-apps', to: 'setup#sample_apps', as: 'sample-apps'
  get '/get-started', to: 'setup#get_started', as: 'get-started'
  get '/pricing', to: 'setup#pricing', as: 'pricing'
  get '/analytics', to: 'analytics#index', as: 'analytics'
  get '/user_growth_json_data', to: 'analytics#user_growth_json_data'
  get '/logs', to: 'analytics#logs', as: 'logs'
  get '/manage', to: 'manage#index', as: 'manage'

  resources :accounts
  # resources :users
  resources :apps
  resources :subscriptions


end

app/controllers/setup_controller.rb
class SetupController < ApplicationController
  before_action :authenticate_user!
  before_action :set_app, only: [:show, :edit, :update, :destroy]
  layout 'user'


  def how_it_works
  end
  
  def mobileapps
	  
  end
  
  def get_started
    
  end

  def pricing   
  end

  def sample_apps
  end
  
  

end

app/views/setup/_form.html.erb
<%= form_for([:users, @app], local: true) do |form| %>

  <% if app.errors.any? %>
    <div class="error_explanation">
      <ul>
        <% app.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>

      <h4>Create a new OpenID Connect Client (relying party)</h4>
      <p>You can provision a new client application here. Please note that you need to implement an OpenID Connect Client on your app first. You can take a look at our <a href="https://deauthorized.github.io/documentation-0.1/" target="_blank">docs for some code examples</a>        on how to accomplish that.</p>
      <p> If you create an app and did not enter the correct data, you cannot revert and edit it. </p>
      <p> If you have any questions please use the chat window to the lower right hand corner of your screen and ask questions.</p>

      <div class="form-group">
        <%= form.label :domain, "Client Domain Name http://" %>
          <%= form.text_field :domain, class: "form-control", placeholder: "http://mydomain.com" %>
      </div>

      <div class="form-group">
        <%= form.label :platform, "Platform Type" %>
          <%= form.select :platform, [['Web', 'web']], {}, { class: "form-control" } %>
      </div>

      <div class="form-group">
        <%= form.label :openid_redirect_urls, "OpenID Callback URL on Client Domain" %>
          <%= form.text_area :openid_redirect_urls, rows: "5", class: "form-control", placeholder: "http://mydomain.com/oauth/callback OR http://mydomain.com/openid_auth_callback" %>
      </div>

      <div class="form-group">
        <%= form.submit class: "btn btn-large btn-success" %>
          <%= link_to 'Back', apps_path, class: "btn btn-link" %>
      </div>
      <% end %>

app/views/setup/basic.html.erb
<div class="row">
    <div class="col-md-6">
        <h1>Step 1:</h1>
        <h2>Deploy an app of your choice</h2>
        <h4>After you deploy, you need to configure the heroku app, then you can fininsh this setup.</h4>
        <br>
        <div class="row d2-row">
            <div class="col-md-6">
                <div class="lang-title">
                    Ruby on Rails
                </div>
            </div>
            <div class="col-md-6">
                <a href="https://heroku.com/deploy?template=https://github.com/Deauthorized/rails-5.1-openid-sample" target="_blank">
                    <img src="https://www.herokucdn.com/deploy/button.svg" alt="Deploy">
                </a>
            </div>
        </div>
        <div class="row d2-row">
            <div class="col-md-6">
                <div class="lang-title">
                    Node JS
                </div>
            </div>
            <div class="col-md-6">
                <a href="https://heroku.com/deploy?template=https://github.com/Deauthorized/rails-5.1-openid-sample" target="_blank">
                    <img src="https://www.herokucdn.com/deploy/button.svg" alt="Deploy">
                </a>
            </div>
        </div>
        <div class="row d2-row">
            <div class="col-md-6">
                <div class="lang-title">
                    Python
                </div>
            </div>
            <div class="col-md-6">
                <a href="https://heroku.com/deploy?template=https://github.com/Deauthorized/rails-5.1-openid-sample" target="_blank">
                    <img src="https://www.herokucdn.com/deploy/button.svg" alt="Deploy">
                </a>
            </div>
        </div>
        <div class="row d2-row">
            <div class="col-md-6">
                <div class="lang-title">
                    PHP
                </div>
            </div>
            <div class="col-md-6">
                <a href="https://heroku.com/deploy?template=https://github.com/Deauthorized/rails-5.1-openid-sample" target="_blank">
                    <img src="https://www.herokucdn.com/deploy/button.svg" alt="Deploy">
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <h1>Step 2:</h1>
        <h2>Create the ClientID and Client Secret for the Heroku App </h2>
        <div class="row">
            <div class="col-md-12">
                <%= render 'form', app: @app %>
            </div>
        </div>
    </div>
</div>

app/views/setup/get_started.html.erb
<div class="container">
  <div class="col-md-10 offset-md-1">
    <div class="row">
      <h2>Welcome to Deauthorized</h2>
    </div>
    <div class="row">
      <br>
      <p>
        <b>
      <i>Please note: This product is still under development and should not be used in a production environment.</i>
    </b>
      </p>
      <p>Thanks for joining our biometric authentication platform. We created several OpenID Client sample applications to get a biometric authentication solution online in 10 minutes. If you have any issues while installing, contact us on the support channel
        in the bottom right corner. We will be available to answer questions and help you get your apps installed and connected to the identity provider. </p>
      <br>
    </div>

    <%= render "installation" %>
  </div>
</div>

app/views/setup/how_it_works.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 text-center">
            <h2>FIDO UAF - Biometric Encryption Protocol</h2>
            <div class="" style="margin-top:0px">
                <!-- <div class="architecture"></div> -->
                <%= image_tag('deauthorized-architecture.png', size: '700x500', class: 'mobile-resize') %>
            </div>
        </div>
        <div class="col-md-5 offset-md-1">
            <div>
                <h2>Login with FIDO UAF</h2>
                <h4 class="t-60">1. Register and create an OpenID Client.</h4>
                <h4>2. Install OpenID Connect. </h4>
                <h4>3. Request auth using QR + fingerprint.</h4>
                <h4>4. FIDO UAF Protocol (the magic).</h4>
                <h4>5. Secure Authentication.</h4>

            </div>
            <%= link_to "Setup OpenID Connect and FIDO UAF", users_create_open_id_app_url, class: "btn btn-lg btn-primary t-60 text-center" %>

        </div>
    </div>
</div>

app/views/setup/mobile_apps.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-1">
      <div class="">
        <h2>Mobile Apps</h2>
        <p>Our mobile app stores unique encryption keys for each OpenID Connect Client and the QR provides all the OpenID Connect Identity Provider information. You can backup, store, and sync your encryption keys on Dropbox like a password keeper. If you
          ever lose your device, you can restore your encryption keys from Dropbox with a password. We do not store your keys anywhere on our service, so you are completely in charge of your keys and their security.
          <%= link_to "Get started now.", get_started_path %>
        </p>
      </div>
    </div>

    <div class="col-md-4 text-center">
      <%= image_tag('da-mobile-app.png', size: '275x565') %>
    </div>

  </div>
</div>

app/views/setup/pricing.html.erb
<div class="container">
    <div class="price-box">
        <form class="form-horizontal form-pricing" role="form">
            <div class="price-slider">
                <h4 class="">Amount</h4>

                <div class="col-sm-12">
                    <div id="slider"></div>
                </div>
            </div>
            <div class="price-form">
                <div class="form-group">
                    <label for="amount" class=" control-label">Amount ($): </label>
                    <span class="help-text">Please choose your amount</span>

                    <div class="col-sm-6">
                        <input type="hidden" id="amount" class="form-control">

                        <p class="price lead" id="amount-label"></p>
                        <span class="price">.00</span>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- <div class="container">
    <div class="">
        <div class="row">
            <div class="col-sm-6">
                <form class="form-horizontal form-pricing" role="form">
                    <div class="price-slider">
                        <div class="row">
                            <h4 class="">Plan Type</h4>
                            <div class="btn-group btn-group-justified">
                                <div class="btn-group btn-group-lg">
                                    <button type="button" class="btn btn-primary btn-lg btn-block month active-month selected-month" id='24month'>Developer</button>
                                </div>
                                <div class="btn-group btn-group-lg">
                                    <button type="button" class="btn btn-primary btn-lg btn-block month" id='18month'>Enterprise</button>
                                </div>
                            </div>

                            <h4 class="">Term</h4>
                            <input name="sliderVal" type="hidden" id="sliderVal" value='0' readonly="readonly" />
                            <input name="month" type="hidden" id="month" value='24month' readonly="readonly" />
                            <input name="term" type="hidden" id="term" value='quarterly' readonly="readonly" />
                            <div class="btn-group btn-group-justified">
                                <div class="btn-group btn-group-lg">
                                    <button type="button" class="btn btn-primary btn-lg btn-block term active-term selected-term" id='quarterly'>Annually</button>
                                </div>
                                <div class="btn-group btn-group-lg">
                                    <button type="button" class="btn btn-primary btn-lg btn-block term" id='monthly'>Monthly</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="price-slider">
                        <h4 class="">Number of Users</h4>
                        <span>Minimum $100K is required</span>
                        <div class="col-sm-12">
                            <div id="slider_amirol"></div>
                        </div>
                    </div>

            </div>
            <div class="col-sm-6">
                <div class="price-form">

                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <label for="amount_amirol" class="control-label">Annually ($): </label>
                                <span class="help-text">Amount that you need to pay</span>
                            </div>
                            <div class="col-sm-6">
                                <input type="hidden" id="amount_amirol" class="form-control">
                                <input class="price lead" name="totalprice" type="text" id="total" disabled="disabled" style="" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <label for="amount_amirol" class="control-label">Monthly ($): </label>
                                <span class="help-text">Amount that you need to pay</span>
                            </div>
                            <div class="col-sm-6">
                                <input type="hidden" id="amount_amirol" class="form-control">
                                <input class="price lead" name="totalprice12" type="text" id="total12" disabled="disabled" style="" />
                            </div>
                        </div>
                    </div>

                    <div style="margin-top:30px"></div>
                    <hr class="style">

                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">Proceed
                <span class="glyphicon glyphicon-chevron-right"></span>
              </button>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <%= image_tag('payment.png', class: "img-responsive payment") %>
                        </div>
                    </div>

                </div>

                </form>
            </div>
        </div>

    </div>

</div> -->